### ISSUE TITLE
libatomic.so.1: cannot open shared object file

### ISSUE THREAD

**Issue by probonopd** [intika/UGChrome#3] opened 2018-12-27 14:57 UTC
https://www.appimagehub.com/p/1265177/startdownload?file_id=1542708924&file_name=ungoogled-chromium_70.0.3538.110-1_linux.AppImage&file_type=application/x-executable&file_size=91692520

```
me@host:~$ Downloads/ungoogled-chromium_70.0.3538.110-1_linux.AppImage 
/tmp/.mount_ungoogL0LXkr/opt/google/chrome/chrome: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
me@host:~$ cat /etc/os-release 
NAME="KDE neon"
VERSION="Developer Edition"
ID=neon
ID_LIKE="ubuntu debian"
PRETTY_NAME="KDE neon Developer Edition"
VERSION_ID="18.04"
HOME_URL="http://neon.kde.org/"
SUPPORT_URL="http://neon.kde.org/"
BUG_REPORT_URL="http://bugs.kde.org/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

Looks like `libatomic.so.1` needs to be bundled inside the AppImage.

**Comment by intika** [comment] 2018-12-27 20:59
is it the only library that is missing ? can you please check

**Comment by probonopd** [comment] 2018-12-27 21:26
Yes, seems to be the only one, at least on `xubuntu-18.04-desktop-amd64.iso`.

As a rule of thumb, all libraries not listed on https://github.com/AppImage/pkg2appimage/blob/master/excludelist should be bundled.

**Comment by intika** [comment] 2018-12-27 22:49
Its also the case for https://github.com/AppImage/pkg2appimage/blob/master/recipes/Google_Chrome.yml too i guess... 

Are you adding it to Chrome recipe as well ?

**Comment by probonopd** [comment] 2018-12-27 22:54
Just tested the Chrome recipe, nothing there seems to require libatomic...

**Comment by intika** [comment] 2018-12-28 01:18
I guess i have to add libatomic to `packages` under https://github.com/Eloston/ungoogled-chromium/blob/master/packaging/linux_simple/ungoogled-chromium.yml

the same way you did here https://github.com/AppImage/pkg2appimage/commit/a8bdd5ea0b7daab54ab2f8f7af31ab3e59d4420d for VSCode.yml

?

**Comment by probonopd** [comment] 2018-12-28 01:46
Yes, that might work.

**Comment by intika** [comment] 2018-12-29 18:34
should be fixed here https://github.com/Eloston/ungoogled-chromium/pull/649/ i am uploading the binaries i will let you know to test :)

**Comment by intika** [comment] 2018-12-29 19:04
Okay it's uploaded can you please check and let me know https://github.com/ungoogled-software/ungoogled-chromium-binaries/pull/47

https://www.opendesktop.org/p/1265177/

**Closed as completed by intika** 2018-12-29 19:04 UTC

**Comment by intika** [comment] 2018-12-29 23:29
Thank you again for your feedback, if it's not too much asking, i have an other appimage for the build of this repo https://www.opendesktop.org/p/1265481/ can you please tell me if the problem is present in that one ? 

Thanks you very much (this is because this version is without sysroot)

**Comment by probonopd** [comment] 2018-12-29 23:35
xubuntu-18.04-desktop-amd64.iso says:

```
$ /home/me/Downloads/ungoogled-chromium_71.0.3578.98-2_linux.AppImage 
/tmp/.mount_ungoogyXeA9N/opt/google/chrome/chrome: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
```

Semi-OT: I have to admit that I am now confused by the different "Ungoogled Chromium", "Chromium (ungoogled)", "UGChrome" etc. versions. I think it would be best if there was _one_ authoritative source for Ungoogled Chromium, this would make things much less confusing. Or else use entirely different branding.

**Comment by intika** [comment] 2018-12-30 00:15
this version may be have at most 100 users... it's just my personal build with those features: 

- Double Click Close Tab
- Build without sysroot 
- Build with those additional flags (rtc_libvpx_build_vp9=false use_system_harfbuzz=false)

Some of them i can not upstream... also i am not advertising this fork not want it to become popular. the main purpose of my question was to see exactly from where the fix came, and apparently it came from sysroot integration not  by adding libatomic1 to the package list may be i am miss spelling it or something i will may be further debug it... but the most important is the main ungoogled chromium build, which is fixed

i forget thank you very much for reporting back :)
